CREATE TABLE BOARDING_PASS_ERROR
(
    DELIVERY_ID        VARCHAR2(40)         REFERENCES BOARDING_PASS_DELIVERY (DELIVERY_REQUEST_ID),
    JOURNEY_ID         VARCHAR2(40)         REFERENCES JOURNEY (JOURNEY_ID),
    PASSENGER_ID       VARCHAR2(40)         REFERENCES PASSENGER (PASSENGER_ID),
    ERROR_CODE         VARCHAR2(40)         NOT NULL,
    CONSTRAINT PK_BOARDING_PASS_ERROR PRIMARY KEY (DELIVERY_ID, JOURNEY_ID, PASSENGER_ID)
);
