CREATE TABLE CHECK_IN_REQUEST
(
    ID                  RAW(16) PRIMARY KEY,
    CHECK_IN_ID         RAW(16) NOT NULL REFERENCES CHECK_IN(ID),
    PROVIDER_REQUEST_ID VARCHAR2(32) NOT NULL,
    CREATED_AT          TIMESTAMP NOT NULL
);
