CREATE TABLE PASSENGER
(
    ID                    RAW(16) PRIMARY KEY,
    CHECK_IN_ID           RAW(16) NOT NULL REFERENCES CHECK_IN(ID),
    PROVIDER_PASSENGER_ID NUMBER(16) NOT NULL,
    NAME                  VARCHAR2(64) NOT NULL,
    LAST_NAME             VARCHAR2(64) NOT NULL,
    DATE_OF_BIRTH         DATE NOT NULL
);
