CREATE TABLE SECTION
(
    ID                  RAW(16) PRIMARY KEY,
    PROVIDER_SECTION_ID NUMBER(16) NOT NULL,
    DEPARTURE_AIRPORT   VARCHAR2(3) NOT NULL,
    ARRIVAL_AIRPORT     VARCHAR2(3) NOT NULL,
    DEPARTURE_DATE      TIMESTAMP NOT NULL,
    ARRIVAL_DATE        TIMESTAMP NOT NULL,
    FLIGHT_NUMBER       NUMBER(4) NOT NULL,
    MARKETING_CARRIER   VARCHAR2(2) NOT NULL,
    OPERATING_CARRIER   VARCHAR2(2) NOT NULL,
    PNR                 VARCHAR2(6) NOT NULL
);
