CREATE TABLE GE_SCRIPTS_LOG
  (
    ID VARCHAR2(256 BYTE) NOT NULL ,
    RELEASE_ID     VARCHAR2(20 BYTE) ,
    EXECUTION_DATE DATE ,
    MODULE VARCHAR2(100),
    CONSTRAINT GE_SCRIPTS_LOG_PK PRIMARY KEY ( ID ) ENABLE
  );

 CREATE TABLE GE_RELEASE_LOG
  (
    ID VARCHAR2(20 BYTE) NOT NULL ,
    EXECUTION_DATE DATE ,
    MODULE VARCHAR2(100),
    CONSTRAINT GE_RELEASE_LOG_PK PRIMARY KEY ( ID ) ENABLE
  );
