CREATE TABLE BOARDING_PASS
(
    ID                            RAW(16) PRIMARY KEY,
    CHECK_IN_ID                   RAW(16) NOT NULL REFERENCES CHECK_IN (ID),
    CHECK_IN_REQUEST_ID           RAW(16) NOT NULL REFERENCES CHECK_IN_REQUEST (ID),
    SECTION_ID                    RAW(16) NOT NULL REFERENCES SECTION (ID),
    PASSENGER_ID                  RAW(16) NOT NULL REFERENCES PASSENGER (ID),
    PROVIDER_PASSENGER_JOURNEY_ID NUMBER(16) NOT NULL,
    STATUS_CODE                   VARCHAR2(8) NOT NULL,
    STATUS_REASON                 VARCHAR2(32),
    UPDATED_AT                    TIMESTAMP NOT NULL
);
